---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/api/v1/restaurant_tables":
    get:
      summary: list restaurant_tables
      responses:
        '200':
          description: successful
    post:
      summary: create restaurant_table
      responses:
        '200':
          description: successful
  "/api/v1/restaurant_tables/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show restaurant_table
      responses:
        '200':
          description: successful
    patch:
      summary: update restaurant_table
      responses:
        '200':
          description: successful
    put:
      summary: update restaurant_table
      responses:
        '200':
          description: successful
    delete:
      summary: delete restaurant_table
      responses:
        '200':
          description: successful
  "/api/v1/login":
    post:
      summary: login session
      responses:
        '200':
          description: successful
  "/api/v1/register":
    post:
      summary: register user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
